### ISSUE TITLE
RAM+SDRAM issues

### ISSUE THREAD

**Issue by juanschroeder** [adamhlt/LiteX-CVA6#1]
Hi there,
Thanks for this repo.

Were you able to make ram tests work? Did you try with a real board?

I'm trying with a Nexys4 DDR without success: https://github.com/enjoy-digital/litex/issues/2121

Thanks

**Comment by adamhlt** [comment]
Hello,
Yes I did some test for RAM, but I don't remember the results.
I will do some test the next week and give you my results.

**Comment by juanschroeder** [comment]
Hi. Have you been able to check this? Which FPGA board did you use for this? Thanks

**Comment by adamhlt** [comment]
Hello, I am sorry I am a bit busy, I will try to do it this week.
I am currently working on an Arty-A7 100T.

**Comment by adamhlt** [comment]
After testing, I have the same problem.
I am currently working with different versions of the CVA6, I will tell you if I have an update.
